services:
  frontend:
    build: .
    container_name: rrapp_frontend
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "3000"
    networks:
      - rrapp_network

networks:
  rrapp_network:
    external: true
    name: rr-backv1_rrapp_network